import { OperationType, OperationCategory } from '../types'

interface OperationTypeConfig {
  label: string
  category: OperationCategory
  color: string
  icon: string
  autoGenerated?: boolean
  defaultAmount?: number
  requiresMember?: boolean
  examples?: string[]
}

export const OPERATION_TYPES: Record<OperationType, OperationTypeConfig> = {
  [OperationType.INGRESO_CUOTA]: {
    label: 'Cuota de Socio',
    category: 'INGRESO',
    color: '#4caf50',
    icon: '💰',
    autoGenerated: true, // No se crea manualmente
  },
  [OperationType.INGRESO_DONACION]: {
    label: 'Donación',
    category: 'INGRESO',
    color: '#4caf50',
    icon: '🎁',
  },
  [OperationType.INGRESO_OTRO]: {
    label: 'Otro Ingreso',
    category: 'INGRESO',
    color: '#4caf50',
    icon: '➕',
  },
  [OperationType.GASTO_REPATRIACION]: {
    label: 'Repatriación',
    category: 'GASTO',
    color: '#f44336',
    icon: '✈️',
    defaultAmount: -1500,
    requiresMember: true,
  },
  [OperationType.GASTO_ADMINISTRATIVO]: {
    label: 'Gasto Administrativo',
    category: 'GASTO',
    color: '#f44336',
    icon: '📋',
    examples: ['Tasas Generalitat', 'Sellos', 'Copistería', 'Imprenta'],
  },
  [OperationType.GASTO_BANCARIO]: {
    label: 'Gasto Bancario',
    category: 'GASTO',
    color: '#f44336',
    icon: '🏦',
    examples: ['Comisión anual', 'Mantenimiento cuenta'],
  },
  [OperationType.GASTO_AYUDA]: {
    label: 'Ayuda Social',
    category: 'GASTO',
    color: '#f44336',
    icon: '🤝',
  },
  [OperationType.GASTO_OTRO]: {
    label: 'Otro Gasto',
    category: 'GASTO',
    color: '#f44336',
    icon: '➖',
  },
}

// Helper: obtener config de un tipo
export const getOperationTypeConfig = (type: OperationType) => OPERATION_TYPES[type]

// Helper: obtener solo ingresos
export const getIncomeTypes = (): OperationType[] => {
  return Object.entries(OPERATION_TYPES)
    .filter(([_, config]) => config.category === 'INGRESO' && !config.autoGenerated)
    .map(([type]) => type as OperationType)
}

// Helper: obtener solo gastos
export const getExpenseTypes = (): OperationType[] => {
  return Object.entries(OPERATION_TYPES)
    .filter(([_, config]) => config.category === 'GASTO')
    .map(([type]) => type as OperationType)
}

// Helper: determinar categoría desde tipo
export const getCategoryFromType = (type: OperationType): OperationCategory => {
  return OPERATION_TYPES[type].category
}
